version: '3'
services:
  server: 
    build: ./server
    ports: 
      - "3060:3060"
    environment:
      - "DB_CONNECTION=mongodb://flipreset:flipreset123@ds049288.mlab.com:49288/flipreset"

  web:
    build: ./project
    ports:
      - "3000:3000"
      - "3030:3030"
    environment:
      - "REACT_APP_API_KEY=AIzaSyAHkDGeM9tCKCIYyJ0pKL13fE-ICudCZ3M"
      - "REACT_APP_AUTH_DOMAIN=test1-cf3a2.firebaseapp.com"
      - "REACT_APP_DATABASE_URL=https://test1-cf3a2.firebaseio.com/"
      - "REACT_APP_PROJECT_ID=test1-cf3a2"
      - "REACT_APP_STORAGE_BUCKET=test1-cf3a2.appspot.com"
      - "REACT_APP_MESSAGING_SENDER_ID=521660089302"
      - "REACT_APP_APPID=1:521660089302:web:b3a43bb3b0da115aa21a77"
      - "REACT_APP_MEASUREMENTID=G-CZ9SCS5DQK"
      - "REACT_APP_CONFIRMATION_EMAIL_REDIRECT=http://localhost:3000/"
      - "DB_CONNECTION=mongodb://flipreset:flipreset123@ds049288.mlab.com:49288/flipreset"
      - "REACT_APP_MONGO_URL=http://localhost:3060/"